[colors.primary]
background = "#fdf6e3"
foreground = "#657b83"

[colors.cursor]
cursor     = "#657b83"

[colors.normal]
black      = "#eee8d5"
red        = "#dc322f"
green      = "#859900"
yellow     = "#b58900"
blue       = "#268bd2"
magenta    = "#d33682"
cyan       = "#2aa198"
white      = "#073642"

[colors.bright]
black      = "#fdf6e3"
red        = "#cb4b16"
green      = "#93a1a1"
yellow     = "#586e75"
blue       = "#839496"
magenta    = "#6c71c4"
cyan       = "#586e75"
white      = "#002b36"
