[general]
live_config_reload = true

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[terminal.shell]
program = "/run/current-system/sw/bin/fish"
args = ["--login", "--interactive"]

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[font]
size = 20

[font.normal]
family = 'Aporetic Serif Mono'

[scrolling]
history = 0

[window]
dynamic_padding = true
opacity = 1
decorations = "None"

[window.dimensions]
columns = 112
lines = 24

[window.padding]
x = 8
y = 8

[mouse]
hide_when_typing = true
